package com.vehisales.platform.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.vehisales.platform.api.dto.CalculateOnRoadCostResponse;
import com.vehisales.platform.api.dto.ExportQuoteRequest;
import com.vehisales.platform.api.dto.QuoteHistoryRecord;
import com.vehisales.platform.domain.QuoteHistory;
import com.vehisales.platform.domain.Vehicle;
import com.vehisales.platform.exception.ResourceNotFoundException;
import com.vehisales.platform.repository.QuoteHistoryRepository;
import com.vehisales.platform.repository.VehicleRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class QuoteHistoryService {

    private final QuoteHistoryRepository quotes;
    private final VehicleRepository vehicleRepository;
    private final OnRoadCostService onRoadCostService;
    private final ObjectMapper objectMapper;
    private final JdbcTemplate jdbcTemplate;

    @EventListener(ApplicationReadyEvent.class)
    public void ensureTable() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS quote_history (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_name VARCHAR(200) NOT NULL,
                    customer_address VARCHAR(400),
                    vehicle_id BIGINT,
                    brand_code VARCHAR(40),
                    vehicle_name VARCHAR(180),
                    location_id BIGINT,
                    location_name VARCHAR(160),
                    category_id BIGINT,
                    color VARCHAR(80),
                    usage_type VARCHAR(20),
                    language VARCHAR(8),
                    include_optional BOOLEAN NOT NULL DEFAULT FALSE,
                    list_price NUMERIC(18,2),
                    sale_price NUMERIC(18,2),
                    discount_amount NUMERIC(18,2),
                    deposit NUMERIC(18,2),
                    on_road_total NUMERIC(18,2),
                    payload TEXT,
                    created_at TIMESTAMP NOT NULL
                )
                """);
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS quote_history_name_idx ON quote_history (customer_name)");
    }

    @Transactional
    public QuoteHistoryRecord saveFromRequest(ExportQuoteRequest request) {
        Vehicle vehicle = vehicleRepository.findByIdAndActiveTrue(request.vehicleId())
                .orElseThrow(() -> new ResourceNotFoundException("Vehicle", request.vehicleId()));
        CalculateOnRoadCostResponse calc = onRoadCostService.calculate(request.toCalculateRequest());
        return persist(request, calc, vehicle);
    }

    @Transactional
    public QuoteHistoryRecord persist(ExportQuoteRequest request, CalculateOnRoadCostResponse calc, Vehicle vehicle) {
        String name = request.customerName() == null ? "" : request.customerName().trim();
        if (name.isEmpty()) {
            throw new IllegalArgumentException("Customer name is required");
        }
        QuoteHistory recent = quotes
                .findFirstByCustomerNameIgnoreCaseAndVehicleIdOrderByCreatedAtDesc(name, request.vehicleId())
                .orElse(null);
        if (recent != null
                && sameAmount(recent.getOnRoadTotal(), calc.estimatedOnRoadTotal())
                && recent.getCreatedAt() != null
                && Duration.between(recent.getCreatedAt(), Instant.now()).toMinutes() < 2) {
            return toRecord(recent);
        }
        QuoteHistory row = QuoteHistory.builder()
                .customerName(name)
                .customerAddress(trimToNull(request.customerAddress()))
                .vehicleId(request.vehicleId())
                .brandCode(vehicle.getBrand() == null ? null : vehicle.getBrand().getCode())
                .vehicleName(calc.vehicleName())
                .locationId(request.locationId())
                .locationName(calc.locationName())
                .categoryId(request.categoryId())
                .color(trimToNull(request.color()))
                .usageType(calc.usageType() == null ? request.usageType() : calc.usageType())
                .language(request.language() == null || request.language().isBlank() ? "vi" : request.language())
                .includeOptional(request.includeOptionalInsurance())
                .listPrice(calc.listPrice())
                .salePrice(calc.salePrice())
                .discountAmount(calc.discountAmount())
                .deposit(calc.deposit())
                .onRoadTotal(calc.estimatedOnRoadTotal())
                .payload(writePayload(request, calc))
                .createdAt(Instant.now())
                .build();
        return toRecord(quotes.save(row));
    }

    @Transactional(readOnly = true)
    public List<QuoteHistoryRecord> list(String query) {
        String text = query == null ? "" : query.trim();
        List<QuoteHistory> rows = text.isEmpty()
                ? quotes.findTop100ByOrderByCreatedAtDesc()
                : quotes.findTop100ByCustomerNameContainingIgnoreCaseOrVehicleNameContainingIgnoreCaseOrderByCreatedAtDesc(text, text);
        return rows.stream().map(this::toRecord).toList();
    }

    @Transactional(readOnly = true)
    public QuoteHistoryRecord get(Long id) {
        return toRecord(quotes.findById(id).orElseThrow(() -> new ResourceNotFoundException("Quote", id)));
    }

    private String writePayload(ExportQuoteRequest request, CalculateOnRoadCostResponse calc) {
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("discountAmount", request.discountAmount());
        payload.put("salePrice", request.salePrice());
        payload.put("deposit", request.deposit());
        payload.put("optionalBodyInsurance", request.optionalBodyInsurance());
        payload.put("registrationServiceFee", request.registrationServiceFee());
        payload.put("micaPlateFee", request.micaPlateFee());
        payload.put("inspectionFee", request.inspectionFee());
        payload.put("accessories", request.accessories());
        payload.put("selectedOfferIds", request.selectedOfferIds());
        payload.put("forgoneOfferIds", request.forgoneOfferIds());
        payload.put("fees", calc.fees());
        payload.put("appliedOfferIds", calc.appliedOfferIds());
        try {
            return objectMapper.writeValueAsString(payload);
        } catch (JsonProcessingException ex) {
            throw new IllegalStateException("Unable to store quote extras", ex);
        }
    }

    private QuoteHistoryRecord toRecord(QuoteHistory row) {
        return new QuoteHistoryRecord(
                row.getId(),
                row.getCustomerName(),
                row.getCustomerAddress(),
                row.getVehicleId(),
                row.getBrandCode(),
                row.getVehicleName(),
                row.getLocationId(),
                row.getLocationName(),
                row.getCategoryId(),
                row.getColor(),
                row.getUsageType(),
                row.getLanguage(),
                row.isIncludeOptional(),
                row.getListPrice(),
                row.getSalePrice(),
                row.getDiscountAmount(),
                row.getDeposit(),
                row.getOnRoadTotal(),
                row.getPayload(),
                row.getCreatedAt()
        );
    }

    private static boolean sameAmount(BigDecimal left, BigDecimal right) {
        if (left == null || right == null) {
            return left == null && right == null;
        }
        return left.compareTo(right) == 0;
    }

    private static String trimToNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }
}
